README.md

Signed-off-by: Jinjing.Zhou <allenzhou@tensorchord.ai>

docs: update README for clarity and new features

---

scripts/train.py
src/vchordrq/algorithm/build.rs
tests/logic/external_build.slt

chore: type check and external test

---

docker/pg-cnpg/Dockerfile

Update enterprise dockerfile

---

.github/workflows/pgrx.yml
.github/workflows/psql.yml
.github/workflows/release.yml
.github/workflows/rust.yml
docker/pgrx.Dockerfile

- `sqllogictest-rs ` doesn't have Linux ARM64 release, tracked [here](https://github.com/risinglightdb/sqllogictest-rs/issues/240)
- add rust-toolchain channel to image tag
- use arm64 runner for clippy/build & release

feat: build multiarch pgrx image

---

Cargo.lock
Cargo.toml
crates/algorithm/src/build.rs
crates/algorithm/src/cache.rs
crates/algorithm/src/lib.rs
crates/algorithm/src/types.rs
src/index/am/am_build.rs
src/index/mod.rs
src/index/storage.rs
src/index/types.rs
tests/logic/pin.slt

feat: pinning index in memory when building, second try

---

crates/simd/build.rs
crates/simd/cshim.c
crates/simd/src/bit.rs
crates/simd/src/emulate.rs
crates/simd/src/f16.rs
crates/simd/src/f32.rs
crates/simd/src/fast_scan/mod.rs
crates/simd/src/lib.rs
crates/simd/src/packed_u4.rs
crates/simd/src/quantize.rs
crates/simd/src/u8.rs
crates/simd_macros/src/lib.rs
crates/simd_macros/src/target.rs
src/index/functions.rs

1. only check simd-related features when dispatching
2. choose SVE implementation only if SVE bits >= 256
3. choose SVE f16 `sum_of_d2` and `sum_of_xy` implementation only if SVE bits >= 512

refactor: remove meaningless target feature requirements

---

.github/workflows/check.yml
crates/simd/src/lib.rs

1. x86_64 runner may not have avx512fp16 feature, so intel SDE is necessary for testing
2. aarch64 runner has short SVE bits, and cannot be used for testing SVE-256 implementation and SVE-512 implementation, so qemu is necessary for testing

fix: test simd operations in emulator

---

README.md
scripts/README.md
scripts/bench.py
scripts/index.py

- add dependency of pgvector
- fix `vector_cos_ops` to `vector_cosine_ops`
- update image version
- fix incorrect QPS count at parallel requests
- when `workers` > 32, QPS will be overestimated
- send the same whole data to all requests, instead of split data for parallel requests
- for dataset `laion-100`, 1000 split to 128 parts will be have a huge negative impact on query startup
- use dburl instead of local password

chore: update readme and scripts with url

---

crates/algorithm/src/types.rs
crates/k_means/src/lib.rs
src/datatype/operators_halfvec.rs
src/datatype/operators_vector.rs
src/index/am/am_build.rs
src/index/am/mod.rs
src/index/functions.rs
src/index/opclass.rs
src/index/scanners/maxsim.rs
src/sql/finalize.sql
tests/logic/multivector.slt
tests/logic/partition.slt

1. add build phase names
2. emit kmeans log
3. emit errors if both `Dot` and `residual_quantiztion` are used
4. update `tuples_done` by estimated value before insertions
5. update `tuples_done` after insertions are done
6. emit errors if `vchordrq_prewarm` is given a partition index
7. rename `maxsim_ip` to `maxsim`

feat: emit INFO when performing kmeans

---

Cargo.lock
Cargo.toml
README.md
crates/k_means/src/lib.rs
src/index/am/am_build.rs
src/index/am/mod.rs
src/index/gucs.rs
tests/logic/rerank_in_table.slt

* encode kmeans progress to build subphase names
* add a new GUC `vchordrq.prererank_filtering` (default to `off`) to control prererank filtering
Kmeans progress phase names look like it.
```
usamoi=# select * from pg_stat_progress_create_index ;
pid   | datid | datname |  relid  | index_relid | command |                            phase                             | lockers_total | lockers_done | current_locker_pid | blo
cks_total | blocks_done | tuples_total | tuples_done | partitions_total | partitions_done 
--------+-------+---------+---------+-------------+---------+--------------------------------------------------------------+---------------+--------------+--------------------+----
----------+-------------+--------------+-------------+------------------+-----------------
156193 | …
```

feat: encode kmeans progress to phase name

---

src/index/gucs.rs
src/index/types.rs
tests/logic/index.slt
tests/logic/partition.slt

This changes default `lists` from `[1000]` to `[]`, and default `probes` to `10` to ` `.
The default value of `1000/10` is too small for big data and may cause issues for small data.
`lists = []` implies "clusters are not used, and all data are in the same set". It's good for small data.

chore: change default lists and probes to empty

---

crates/algorithm/src/build.rs
crates/algorithm/src/bulkdelete.rs
crates/algorithm/src/insert.rs
crates/algorithm/src/lib.rs
crates/algorithm/src/maintain.rs
crates/algorithm/src/operator.rs
crates/algorithm/src/rerank.rs
crates/algorithm/src/search.rs
crates/algorithm/src/tape.rs
crates/algorithm/src/tuples.rs
crates/algorithm/src/vectors.rs
crates/k_means/src/lib.rs
crates/rabitq/src/binary.rs
crates/rabitq/src/block.rs
crates/rabitq/src/lib.rs
src/datatype/typmod.rs
src/index/algorithm.rs
src/index/am/am_build.rs
src/index/am/mod.rs
src/index/gucs.rs
src/index/scanners/default.rs
src/index/scanners/maxsim.rs
src/index/scanners/mod.rs
tests/logic/multivector.slt

1. rename `max_maxsim_tuples` to `maxsim_refine`; leave it a default value `0`
2. remove `allows_skipping_rerank`; use estimated distance for vectors whose distance is not calculated

refactor: remove allows_skipping_rerank

---

src/index/gucs.rs
src/index/vchordg/am/mod.rs
src/index/vchordrq/am/mod.rs
src/sql/finalize.sql
tests/vchordrq/recall.slt

```sql
> SELECT vchordrq_evaluate_query_recall(query_text =>$$SELECT ctid FROM test ORDER BY val <-> '[0.5, 0.25, 1.0]' LIMIT 10$$);
vchordrq_evaluate_query_recall 
--------------------------------
1
(1 row)
> SELECT vchordrq_evaluate_query_recall(query_text => $$SELECT ctid FROM test ORDER BY val <-> '[0.5, 0.25, 1.0]' LIMIT 100$$, exact_search=>true);
vchordrq_evaluate_query_recall 
--------------------------------
1
> SELECT vchordrq_evaluate_query_recall(query_text => $$SELECT ctid FROM test WHERE FALSE' LIMIT 100$$, exact_search=>true);
vchordrq_evaluate_query_recall 
--------------------------------
NaN
(1 row)
```

feat: query recall eval func

---

Cargo.lock
Cargo.toml
crates/make/Cargo.toml
crates/make/src/main.rs
crates/simd/Cargo.toml
crates/simd_macros/Cargo.toml
crates/vchordrq/Cargo.toml
taplo.toml

Profile `release` includes debug information for profiling, while it unnecessarily increased the binary size for users. Now disable debuginfo for profile `release` and add a profile `prof` for profiling. The size of the release binary has been reduced from 96.9MB to 4.4MB.

fix: disable debuginfo on profile release

---

src/sql/finalize.sql
tests/vchordrq/recall.slt

Pick from #295, only with change of `vchordrq_evaluate_query_recall`

chore: add accu_probes to recall function

---

crates/simd/src/fast_scan.rs
crates/simd/src/lib.rs

The compiler refuses to inline the intrinsics in `stdarch` unless the baseline is raised with target-cpu. This is strange.

feat: ppc64 BE scan

---

crates/rabitq/build.rs
crates/rabitq/src/rotate.rs

fix: apply same rotation on big endian

---

Cargo.lock
Cargo.toml
scripts/train.py
src/index/functions.rs
src/index/gucs.rs
src/index/scanners.rs
src/index/vchordg/am/mod.rs
src/index/vchordg/scanners/default.rs
src/index/vchordrq/am/mod.rs
src/index/vchordrq/scanners/default.rs
src/index/vchordrq/scanners/maxsim.rs
src/lib.rs
src/recorder/hook.rs
src/recorder/mod.rs
src/recorder/text.rs
src/recorder/types.rs
src/recorder/worker.rs
src/sql/finalize.sql
tests/vchordrq/recall.slt

job: +psql_windows
job: +psql_macos
job: +check_debian
job: +psql_alpine
* `vchordrq.query_sampling_enable`: Whether to enable the query logger
* bool, default off
* `vchordrq.query_sampling_max_records`: Maximum logged queries per index
* int, 0 to **10000**, default 0
* `vchordrq.query_sampling_rate`: Sample rate of query to be logged
* float, 0 to 1, default 0.01 (for 1% pick rate)
* `vchordrq_sampled_queries(index: Oid)`: Show logged queries for the given index
* `vchordrq_sampled_vectors(index: Oid)`: Get logged vector samples (only for internal use).
* `vchordrq_sampled_queries`: Show logged queries for all indexes which you have access
```sql
-- Preset
CREATE TABLE t (id SERIAL PRIMARY KEY, val vector(3));
INSERT INTO t (val)
SELECT ARRAY[i * 0.0001, i * 0.00005, i * …
```

feat: record queries by sqlite

---

crates/k_means/src/lib.rs
crates/rabitq/src/bit.rs
crates/rabitq/src/packing.rs
crates/vchordrq/src/bulkdelete.rs
crates/vchordrq/src/cache.rs
crates/vchordrq/src/insert.rs
crates/vchordrq/src/maintain.rs
crates/vchordrq/src/prewarm.rs
crates/vchordrq/src/search.rs
crates/vchordrq/src/types.rs
src/index/vchordg/am/am_build.rs
src/index/vchordrq/am/am_build.rs
src/index/vchordrq/am/mod.rs
src/index/vchordrq/types.rs
tests/vchordg/sequential_build.slt
tests/vchordrq/sequential_build.slt

1. fixes `build.pin` does not work if the build is not parallelized
2. adds fast path if `lists <= probes && !residual_quantization`
3. fixes cost estimation if `lists < probes`
4. adds `build.default` to reduce special handling
5. rotate vectors after all kinds of `build` to reduce special handling

chore: multiple fixes and fast paths

---

Cargo.lock
crates/algo/src/lib.rs
crates/vchordg/src/bulkdelete.rs
crates/vchordg/src/types.rs
crates/vchordrq/src/build.rs
crates/vchordrq/src/bulkdelete.rs
crates/vchordrq/src/cache.rs
crates/vchordrq/src/centroids.rs
crates/vchordrq/src/insert.rs
crates/vchordrq/src/lib.rs
crates/vchordrq/src/prewarm.rs
crates/vchordrq/src/rerank.rs
crates/vchordrq/src/search.rs
crates/vchordrq/src/tuples.rs
crates/vchordrq/src/types.rs
crates/vchordrq/src/vectors.rs
src/datatype/typmod.rs
src/index/storage.rs
src/index/vchordg/algo.rs
src/index/vchordg/am/am_build.rs
src/index/vchordrq/algo.rs
src/index/vchordrq/am/am_build.rs
src/index/vchordrq/am/mod.rs
src/index/vchordrq/types.rs

```sql
create index on laion1m768_train using vchordrq (embedding vector_ip_ops) with (options = $$
build.pin = 2
build.internal.lists = [256, 4096]
build.internal.build_threads = 20
build.internal.spherical_centroids = true
degree_of_parallelism = 40
$$);
```
`degree_of_parallelism` is 32 by default. It reduces lock contention during insertion, especially, in a build where `lists.len() != 1`.
`build.pin` is `-1` by default. `build.pin = 2` caches almost everything in memory, which speeds build but spends more memory. `build.pin = false` and `build.pin = true` still works, and they're mapped to `build.pin = -1` and `build.pin = 1`.

perf: reduce lock contention
