.github/workflows/cla.yml

https://github.com/tensorchord/VectorChord/pull/78

fix: Use a personal token in CLA

---

README.md
scripts/index.py
src/algorithm/build.rs
src/algorithm/insert.rs
src/algorithm/k_means.rs
src/algorithm/prewarm.rs
src/algorithm/scan.rs
src/algorithm/tuples.rs
src/algorithm/vacuum.rs
src/gucs/executing.rs
src/types.rs
tests/logic/index.slt

feat: k-means tree

---

src/gucs/executing.rs
src/index/am_scan.rs

feat: max_scan_tuples

---

.github/workflows/release.yml
README.md
docker/Dockerfile
docker/binary.Dockerfile

- close #102 
Tested https://github.com/tensorchord/VectorChord/actions/runs/11968955634
Images can be found in https://hub.docker.com/r/tensorchord/vchord-postgres/tags

chore: build multiarch docker images

---

src/utils/k_means.rs
src/vchordrq/algorithm/build.rs
src/vchordrq/types.rs
src/vchordrqfscan/algorithm/build.rs
src/vchordrqfscan/types.rs

feat: improve internal build

---

README.md

Ref #79 
Preview: https://github.com/gaocegege/VectorChord/tree/refine

chore(README): Add some benchmark data

---

.github/workflows/psql.yml
.github/workflows/release.yml
README.md
scripts/README.md
tools/package.sh

- clean the target option
- fix release CI
- update readme about how to use the vectorchord-pgrx image

chore: fix the psql & release CI target, update readme

---

src/vchordrqfscan/algorithm/build.rs
src/vchordrqfscan/algorithm/insert.rs
src/vchordrqfscan/algorithm/tuples.rs
src/vchordrqfscan/index/am.rs

pick #106, #147 and #149 to vchordrqfscan

fix: pick feat back to vchordrqfscan

---

src/algorithm/prewarm.rs

https://github.com/tensorchord/VectorChord/issues/171#issuecomment-2604327460

fix: correct output of prewarm

---

.github/workflows/check.yml
crates/algorithm/src/build.rs
crates/algorithm/src/insert.rs
crates/algorithm/src/lib.rs
crates/algorithm/src/rerank.rs
crates/algorithm/src/search.rs
crates/algorithm/src/tuples.rs
crates/algorithm/src/types.rs
crates/k_means/src/lib.rs
src/index/am/am_build.rs
src/index/am/am_scan.rs
src/index/gucs.rs
src/index/types.rs
tests/logic/rerank_in_table.slt

feat: rerank by fetching vectors in heap table

---

.github/workflows/release.yml

chore: add ghcr image

---

Cargo.lock
crates/algorithm/Cargo.toml
crates/algorithm/src/select_heap.rs

fix: remove heapify

---

.github/workflows/check.yml
README.md
src/index/am/am_build.rs

pull request in docs repo: https://github.com/tensorchord/pgvecto.rs-docs/pull/106
[Rendered README.md](https://github.com/usamoi/VectorChord/blob/readme/README.md)
[Preview docs](https://pgvecto-rs-docs-83ki0aiml-tensorchord.vercel.app/vectorchord/getting-started/overview.html)

readme: move docs to docs repo

---

.cargo/config.toml
build.rs
crates/algorithm/src/build.rs
crates/algorithm/src/freepages.rs
crates/algorithm/src/insert.rs
crates/algorithm/src/lib.rs
crates/algorithm/src/maintain.rs
crates/algorithm/src/operator.rs
crates/algorithm/src/prewarm.rs
crates/algorithm/src/rerank.rs
crates/algorithm/src/search.rs
crates/algorithm/src/select_heap.rs
crates/algorithm/src/tape.rs
crates/algorithm/src/tuples.rs
crates/algorithm/src/vectors.rs
crates/rabitq/src/binary.rs
crates/rabitq/src/block.rs
crates/rabitq/src/lib.rs
src/index/algorithm.rs
src/index/am/mod.rs
src/index/gucs.rs
src/index/scanners/maxsim.rs
src/index/scanners/mod.rs

Enable it by `SET vchordrq.allows_skipping_rerank TO on`.
Skip rerank by enabling it and `SET vchordrq.epsilon = 0.0`.

feat: allows skipping rerank

---

.github/workflows/release.yml

Before
https://github.com/cutecutecat/VectorChord/actions/runs/14394009275/job/40366384594
After
https://github.com/cutecutecat/VectorChord/actions/runs/14394625976/job/40368000745

fix: release env vars

---

README.md

docs: fix readme callout

---

README.md

- Update GHCR recommendation to `0.4.2`
- Add release/download badge about GHCR
- Introduce DeepWiki badge to enable auto refresh of LLM generated [wiki](https://deepwiki.com/tensorchord/VectorChord)
- Update lists `lists` parameter divide from `100M` to `50M` based on `Cohere-50M` experiment result

chore: update readme with version and badges

---

.cargo/config.toml
Cargo.lock
build.rs
crates/make/Cargo.toml
crates/make/src/main.rs
crates/simd/Cargo.toml
crates/simd/build.rs
crates/vchordg/src/build.rs
crates/vchordg/src/insert.rs
crates/vchordg/src/maintain.rs
crates/vchordg/src/operator.rs
crates/vchordg/src/prune.rs
crates/vchordg/src/tuples.rs
crates/vchordg/src/types.rs
src/index/gucs.rs
src/index/vchordg/am/am_build.rs

disables `beam` by default
job: +psql_macos
job: +psql_windows

feat: improve prune

---

Cargo.lock
Cargo.toml
crates/k_means/Cargo.toml
crates/make/Cargo.toml
crates/make/src/main.rs
crates/simd/Cargo.toml
crates/simd/cshim/aarch64.c
crates/simd/src/f16.rs
crates/simd/src/f32.rs
crates/simd/src/fast_scan.rs
crates/simd/src/quantize.rs
crates/simd_macros/src/lib.rs
src/lib.rs

fix compilation on aarch64_be

---

README.md

blocked by https://github.com/tensorchord/pgvecto.rs-docs/pull/143

readme: sync with docs
